USE proyecto_plantquest;
INSERT INTO proyecto_plantquest.answer (text, question) VALUES
                                        ('Menos de 3 horas', 1),
                                        ('De 3 a 6 horas', 1),
                                        ('De 6 a 9 horas', 1),
                                        ('Más de 9 horas', 1),
                                        ('Baja', 2),
                                        ('Indirecta o filtrada', 2),
                                        ('Brillante', 2),
                                        ('Directa', 2),
                                        ('Norte', 3),
                                        ('Sur', 3),
                                        ('Este', 3),
                                        ('Oeste', 3),
                                        ('Pequeño', 4),
                                        ('Mediano', 4),
                                        ('Grande', 4),
                                        ('En la mesa', 5),
                                        ('En el suelo', 5),
                                        ('Colgando', 5),
                                        ('Muy poca (menos de 35%)', 6),
                                        ('Moderada (alrededor de 45%)', 6),
                                        ('Mucha (más de 50%)', 6),
                                        ('Menos de 20º', 6),
                                        ('De 20º a 25º', 7),
                                        ('De 25º a 30º', 7),
                                        ('Más 30º', 7),
                                        ('Tengo mascotas', 8),
                                        ('Tengo niños', 8),
                                        ('Ambos', 8),
                                        ('Ninguno', 8),
                                        ('Una vez a la semana', 9),
                                        ('Cada dos semanas', 9),
                                        ('Una vez al mes o menos', 9),
                                        ('Plantas de hojas verdes', 10),
                                        ('Plantas que florezcan', 10),
                                        ('Cactus y crasas', 10);
